// <auto-generated />
using System;
using CurrencyConverterAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CurrencyConverterAPI.Migrations
{
    [DbContext(typeof(ConvertTransactionContext))]
    partial class ConvertTransactionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("CurrencyConverterAPI.Models.ConvertTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConversionRate")
                        .HasColumnType("REAL");

                    b.Property<string>("CurrencyFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyTo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateHourUTC")
                        .HasColumnType("TEXT");

                    b.Property<double>("QuoteRate")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ConvertTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
