version: '3.4'

services:
  currencyconverterapi:
    container_name: currencyconverterapi
    image: currencyconverterapi
    environment:
        - PORT=5000
    ports:
        - 5000:5000
    build:
      context: .
      dockerfile: CurrencyConverterAPI/Dockerfile

networks:
  default:
    driver: bridge