name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'    

    - name: Build
      run: dotnet build CurrencyConverterAPI.sln

    - name: Test
      run: dotnet test CurrencyConverterTests

    - name: Deploy
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'dfl-currency-converter' }}
        CONTAINER_NAME: ${{ 'currencyconverterapi' }}
      run: |
        docker login --username=daniel.filippolima@gmail.com --password=$HEROKU_API_KEY registry.heroku.com
        docker tag $CONTAINER_NAME registry.heroku.com/my-app-12355/web
        docker push registry.heroku.com/$CONTAINER_NAME/web
        heroku container:release web --app=$CONTAINER_NAME
